services:
  web-server:
    image: fizzbuzz-web-server:local
    build:
      context: .
      dockerfile: apps/web-server/Dockerfile
    pull_policy: build
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - fizzbuzz-network

  web-dashboard:
    image: fizzbuzz-web-dashboard:local
    build:
      context: .
      dockerfile: apps/web-dashboard/Dockerfile
    pull_policy: build
    ports:
      - "5173:80"
    depends_on:
      - web-server
    networks:
      - fizzbuzz-network

  marketing-landing-page:
    image: fizzbuzz-marketing-landing-page:local
    build:
      context: .
      dockerfile: apps/marketing-landing-page/Dockerfile
    pull_policy: build
    ports:
      - "8080:80"
    depends_on:
      - web-server
    networks:
      - fizzbuzz-network

networks:
  fizzbuzz-network:
    driver: bridge
