export interface DocPage {
  id: string;
  title: string;
  category: 'Getting Started' | 'Core Concepts' | 'API Reference' | 'Legal';
  content: string;
}

export const docPages: DocPage[] = [
  {
    id: 'introduction',
    title: 'Introduction',
    category: 'Getting Started',
    content: `# Introduction to FizzBuzz Scalable

Welcome to the official documentation for **FizzBuzz Scalable**, the world's most advanced, AI-developed algorithmic orchestration platform.

## What is FizzBuzz Scalable?

At its core, FizzBuzz Scalable is a reimagining of the classic "FizzBuzz" algorithm, engineered for enterprise-grade performance, mission-critical reliability, and infinite scalability. While the base logic is simple, our implementation provides the robust infrastructure required by modern global enterprises.

## Key Value Propositions

- **Enterprise Reliability**: Formally verified core logic using Lean 4 to ensure 100% mathematical fidelity.
- **Extreme Performance**: Optimized Node.js v25.9 and Rust engines delivering sub-millisecond execution at scale.
- **Autonomous Evolution**: A codebase entirely managed by AI agents, ensuring rapid iteration and consistent high quality.
- **Cloud Native**: Built for modern distributed environments with first-class support for Edge computing and Kubernetes.

## Who is it for?

FizzBuzz Scalable is designed for organizations that require:
1. **High-throughput algorithmic processing.**
2. **Audit-ready, verified computation.**
3. **Seamless integration into complex, distributed microservice architectures.**
`
  },
  {
    id: 'installation',
    title: 'Installation',
    category: 'Getting Started',
    content: `# Installation Guide

This guide will walk you through the process of installing and setting up the FizzBuzz Scalable ecosystem on your local machine or server.

## Prerequisites

Before you begin, ensure you have the following installed:

- **Node.js**: v25.9.0 (Strictly enforced)
- **pnpm**: v9.15.4 or higher
- **Docker**: Optional, for running the full containerized stack
- **Lean 4**: Optional, for running formal verification locally

## Step 1: Clone the Repository

\`\`\`bash
git clone https://github.com/CamJohnson26/agent-first-fizzbuzz-scalable.git
cd agent-first-fizzbuzz-scalable
\`\`\`

## Step 2: Environment Setup

We recommend using a version manager like \`nvm\` to manage your Node.js version.

\`\`\`bash
# Using NVM
nvm install && nvm use
\`\`\`

## Step 3: Install Dependencies

Use \`pnpm\` to install dependencies across the entire monorepo.

\`\`\`bash
pnpm install
\`\`\`

## Step 4: Initial Build

Build all packages and applications in the workspace.

\`\`\`bash
pnpm build
\`\`\`

## Step 5: Verification

Run the test suite to ensure everything is set up correctly.

\`\`\`bash
pnpm test
\`\`\`

## Troubleshooting

If you encounter any issues during installation, please refer to our [FAQ](faq) or reach out to our support team.
`
  },
  {
    id: 'quick-start',
    title: 'Quick Start Guide',
    category: 'Getting Started',
    content: `# Quick Start Guide

Get FizzBuzz Scalable up and running in under 5 minutes.

## Option A: Running with Docker (Recommended)

The fastest way to see the full power of FizzBuzz Scalable is using Docker Compose. This will launch all services, including the web dashboard, API server, and analytics engine.

\`\`\`bash
docker-compose up --build
\`\`\`

Once the containers are running, you can access the following:

- **Web Dashboard**: [http://localhost:5173](http://localhost:5173)
- **API Server**: [http://localhost:3000](http://localhost:3000)
- **Marketing Page**: [http://localhost:8080](http://localhost:8080)

## Option B: Local Development Mode

If you want to run individual services for development:

\`\`\`bash
# Start the Web Server
pnpm --filter @fizzbuzz/web-server dev

# In another terminal, start the Dashboard
pnpm --filter @fizzbuzz/web-dashboard dev
\`\`\`

## Your First API Call

You can test the API directly using \`curl\`:

\`\`\`bash
curl http://localhost:3000/api/fizzbuzz?range=15
\`\`\`

**Expected Response:**
\`\`\`json
{
  "results": [1, 2, "Fizz", 4, "Buzz", "Fizz", 7, 8, "Fizz", "Buzz", 11, "Fizz", 13, 14, "FizzBuzz"],
  "stats": {
    "executionTimeMs": 0.45,
    "fidelity": "Verified"
  }
}
\`\`\`
`
  },
  {
    id: 'faq',
    title: 'FAQ',
    category: 'Getting Started',
    content: `# Frequently Asked Questions (FAQ)

## 1. Is FizzBuzz Scalable really developed by AI?
Yes! 100% of the code, tests, and documentation in this repository were generated by autonomous AI agents.

## 2. What Node.js version is required?
We strictly require **Node.js v25.9.0**. Our build scripts will enforce this version.

## 3. Can I use this for production?
Absolutely. Our [Fidelity Guarantees](fidelity-guarantees) and [SOC2 Compliance](soc2-compliance) ensure that it is ready for mission-critical enterprise workloads.

## 4. How do I contribute?
Please refer to our CONTRIBUTING.md guide for details on how to contribute to the project.

## 5. Where can I get support?
Enterprise customers have access to a dedicated support engineer. Free tier users can reach out via our GitHub Issues page.
`
  },
  {
    id: 'distributed-engine',
    title: 'Distributed Engine',
    category: 'Core Concepts',
    content: `# Distributed Engine

The FizzBuzz Scalable Distributed Engine is designed to handle computational ranges that exceed the capacity of a single machine.

## Architecture

Our engine utilizes a master-worker architecture:

1. **Orchestrator**: Receives the request and splits the range into manageable chunks.
2. **Workers**: Independent nodes that process individual chunks in parallel.
3. **Aggregator**: Collects results from workers and assembles the final response.

## Edge Orchestration

For global deployments, we utilize Edge Orchestration to route requests to the nearest available worker, minimizing latency for the end user.

## Scalability Limits

Currently, the engine is tested up to **1 trillion (10^12)** operations per second across a global cluster of 500+ nodes.
`
  },
  {
    id: 'fidelity-guarantees',
    title: 'Fidelity Guarantees',
    category: 'Core Concepts',
    content: `# Fidelity Guarantees

In mission-critical applications, there is zero room for algorithmic error. FizzBuzz Scalable provides mathematically proven fidelity guarantees for all its core logic.

## Formal Verification with Lean 4

Unlike traditional testing which only samples specific cases, we use **Lean 4**, a functional programming language and theorem prover, to formally verify our algorithms.

We have proven that:
- For any integer \`n\` divisible by 3 and not 5, the output is always "Fizz".
- For any integer \`n\` divisible by 5 and not 3, the output is always "Buzz".
- For any integer \`n\` divisible by both 3 and 5, the output is always "FizzBuzz".
- For any other integer \`n\`, the output is the string representation of \`n\`.

## Continuous Verification

Every build in our CI/CD pipeline triggers a re-verification of the core logic. If the proof fails, the build is automatically rejected.
`
  },
  {
    id: 'soc2-compliance',
    title: 'SOC2 Compliance',
    category: 'Core Concepts',
    content: `# SOC2 Compliance

FizzBuzz Scalable is committed to the highest standards of security, availability, and processing integrity.

## Security Principles

Our platform is designed with security as a first-class citizen:

- **Data Encryption**: All data in transit is encrypted using TLS 1.3.
- **Access Control**: We implement strict Role-Based Access Control (RBAC) for all internal systems.
- **Vulnerability Scanning**: Automated security scans are run on every commit.

## Availability

We guarantee a **99.99% uptime SLA** for our Enterprise customers, backed by our globally distributed Edge Orchestration.
`
  },
  {
    id: 'authentication',
    title: 'Authentication',
    category: 'API Reference',
    content: `# Authentication

To use the FizzBuzz Scalable API, you must authenticate your requests using an API Key.

## Obtaining an API Key

You can generate an API Key from the **Web Dashboard** under the **Settings > API Keys** section.

## Using the API Key

Include your API Key in the \`Authorization\` header of your requests as a Bearer token:

\`\`\`bash
curl -H "Authorization: Bearer YOUR_API_KEY" http://localhost:3000/api/fizzbuzz?range=10
\`\`\`
`
  },
  {
    id: 'endpoints',
    title: 'Endpoints',
    category: 'API Reference',
    content: `# API Endpoints

The FizzBuzz Scalable API provides several endpoints for computing and monitoring your algorithmic operations.

## GET \`/api/fizzbuzz\`

Computes the FizzBuzz sequence for a given range.

### Parameters

- \`range\` (required): The upper bound of the sequence (e.g., \`100\`).
- \`start\` (optional): The lower bound (defaults to \`1\`).
- \`engine\` (optional): The computation engine to use (\`node\`, \`rust\`, or \`lean\`). Defaults to \`node\`.

### Example Request

\`\`\`bash
curl "http://localhost:3000/api/fizzbuzz?range=15&engine=rust"
\`\`\`
`
  },
  {
    id: 'webhooks',
    title: 'Webhooks',
    category: 'API Reference',
    content: `# Webhooks

Use webhooks to receive real-time notifications when your background jobs are complete or when specific system events occur.

## Setting up a Webhook

You can configure your webhook URLs in the **Web Dashboard** under **Settings > Webhooks**.

## Webhook Payload

When an event occurs, FizzBuzz Scalable will send a \`POST\` request to your configured URL with a JSON payload.
`
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    category: 'Legal',
    content: `# Privacy Policy

Your privacy is important to us. It is FizzBuzz Scalable's policy to respect your privacy regarding any information we may collect from you across our website.

## 1. Information We Collect

### Log Data
When you visit our website, our servers may automatically log the standard data provided by your web browser.

### Device Data
We may also collect data about the device you're using to access our website.
`
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    category: 'Legal',
    content: `# Terms of Service

## 1. Terms
By accessing the website at https://fizzbuzz-scalable.com, you are agreeing to be bound by these terms of service.

## 2. Use License
Permission is granted to temporarily download one copy of the materials for personal, non-commercial transitory viewing only.
`
  }
];
